name: orury
description: kernel360 Orury! project

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  bloc_concurrency: ^0.2.2
  dart_code_metrics: ^5.7.5
  dio: ^5.3.0
  flutter:
    sdk: flutter
#  provider: ^6.0.1
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  go_router: ^9.0.3
  injectable: ^2.1.2
  json_annotation: ^4.8.1
  logger: ^1.4.0
  mocktail: ^1.0.0
  retrofit: ^4.0.1
  stream_transform: ^2.1.0
  intl:
  lottie:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.2.3
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  shimmer:
  flutter_dotenv:
  firebase_crashlytics: ^3.3.5
  http: ^0.13.3
  fluttertoast: ^8.2.4
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.5
  shared_preferences: ^2.0.7
  image_picker: ^1.0.4

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/svg/orury_splash.png
    - assets/png/
    - lib/global/config/.env