debug: false
management.endpoints.web.exposure.include: "*"
server.port: 8580
logging:
  level:
    com.example.noticeboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
---
spring:
  application.name: orury
  datasource:
    url: ${LOCAL_DB_URL} # configuration에서 추가
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_USER_PASSWORD}
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
      hibernate.globally_quoted_identifiers: true
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated
  thymeleaf3:
    decoupled-logic: true

---
spring:
  config.activate.on-profile: test
  datasource.url: jdbc:h2:mem:testdb